//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace raporkuAPP.RaporServiceAzure {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Admin", Namespace="http://schemas.datacontract.org/2004/07/RaporService")]
    [System.SerializableAttribute()]
    public partial class Admin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_adminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passw_adminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string uname_adminField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_admin {
            get {
                return this.id_adminField;
            }
            set {
                if ((object.ReferenceEquals(this.id_adminField, value) != true)) {
                    this.id_adminField = value;
                    this.RaisePropertyChanged("id_admin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string passw_admin {
            get {
                return this.passw_adminField;
            }
            set {
                if ((object.ReferenceEquals(this.passw_adminField, value) != true)) {
                    this.passw_adminField = value;
                    this.RaisePropertyChanged("passw_admin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string uname_admin {
            get {
                return this.uname_adminField;
            }
            set {
                if ((object.ReferenceEquals(this.uname_adminField, value) != true)) {
                    this.uname_adminField = value;
                    this.RaisePropertyChanged("uname_admin");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Kelas", Namespace="http://schemas.datacontract.org/2004/07/RaporService")]
    [System.SerializableAttribute()]
    public partial class Kelas : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_kelasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nama_kelasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_kelas {
            get {
                return this.id_kelasField;
            }
            set {
                if ((object.ReferenceEquals(this.id_kelasField, value) != true)) {
                    this.id_kelasField = value;
                    this.RaisePropertyChanged("id_kelas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nama_kelas {
            get {
                return this.nama_kelasField;
            }
            set {
                if ((object.ReferenceEquals(this.nama_kelasField, value) != true)) {
                    this.nama_kelasField = value;
                    this.RaisePropertyChanged("nama_kelas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mapel", Namespace="http://schemas.datacontract.org/2004/07/RaporService")]
    [System.SerializableAttribute()]
    public partial class Mapel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_mapelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nama_jurusanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nama_mapelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_mapel {
            get {
                return this.id_mapelField;
            }
            set {
                if ((object.ReferenceEquals(this.id_mapelField, value) != true)) {
                    this.id_mapelField = value;
                    this.RaisePropertyChanged("id_mapel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nama_jurusan {
            get {
                return this.nama_jurusanField;
            }
            set {
                if ((object.ReferenceEquals(this.nama_jurusanField, value) != true)) {
                    this.nama_jurusanField = value;
                    this.RaisePropertyChanged("nama_jurusan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nama_mapel {
            get {
                return this.nama_mapelField;
            }
            set {
                if ((object.ReferenceEquals(this.nama_mapelField, value) != true)) {
                    this.nama_mapelField = value;
                    this.RaisePropertyChanged("nama_mapel");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rapot", Namespace="http://schemas.datacontract.org/2004/07/RaporService")]
    [System.SerializableAttribute()]
    public partial class Rapot : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_kelasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_mapelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_rapotField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_siswaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nilaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string semesterField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_kelas {
            get {
                return this.id_kelasField;
            }
            set {
                if ((object.ReferenceEquals(this.id_kelasField, value) != true)) {
                    this.id_kelasField = value;
                    this.RaisePropertyChanged("id_kelas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_mapel {
            get {
                return this.id_mapelField;
            }
            set {
                if ((object.ReferenceEquals(this.id_mapelField, value) != true)) {
                    this.id_mapelField = value;
                    this.RaisePropertyChanged("id_mapel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_rapot {
            get {
                return this.id_rapotField;
            }
            set {
                if ((object.ReferenceEquals(this.id_rapotField, value) != true)) {
                    this.id_rapotField = value;
                    this.RaisePropertyChanged("id_rapot");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_siswa {
            get {
                return this.id_siswaField;
            }
            set {
                if ((object.ReferenceEquals(this.id_siswaField, value) != true)) {
                    this.id_siswaField = value;
                    this.RaisePropertyChanged("id_siswa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nilai {
            get {
                return this.nilaiField;
            }
            set {
                if ((object.ReferenceEquals(this.nilaiField, value) != true)) {
                    this.nilaiField = value;
                    this.RaisePropertyChanged("nilai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string semester {
            get {
                return this.semesterField;
            }
            set {
                if ((object.ReferenceEquals(this.semesterField, value) != true)) {
                    this.semesterField = value;
                    this.RaisePropertyChanged("semester");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Siswa", Namespace="http://schemas.datacontract.org/2004/07/RaporService")]
    [System.SerializableAttribute()]
    public partial class Siswa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string alamatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_kelasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_siswaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_walikelasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jenis_kelaminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nama_agamaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nama_ayahField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nama_ibuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nama_siswaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomor_ortuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string status_kawinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tempat_lahirField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tgl_lahirField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string alamat {
            get {
                return this.alamatField;
            }
            set {
                if ((object.ReferenceEquals(this.alamatField, value) != true)) {
                    this.alamatField = value;
                    this.RaisePropertyChanged("alamat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_kelas {
            get {
                return this.id_kelasField;
            }
            set {
                if ((object.ReferenceEquals(this.id_kelasField, value) != true)) {
                    this.id_kelasField = value;
                    this.RaisePropertyChanged("id_kelas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_siswa {
            get {
                return this.id_siswaField;
            }
            set {
                if ((object.ReferenceEquals(this.id_siswaField, value) != true)) {
                    this.id_siswaField = value;
                    this.RaisePropertyChanged("id_siswa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_walikelas {
            get {
                return this.id_walikelasField;
            }
            set {
                if ((object.ReferenceEquals(this.id_walikelasField, value) != true)) {
                    this.id_walikelasField = value;
                    this.RaisePropertyChanged("id_walikelas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jenis_kelamin {
            get {
                return this.jenis_kelaminField;
            }
            set {
                if ((object.ReferenceEquals(this.jenis_kelaminField, value) != true)) {
                    this.jenis_kelaminField = value;
                    this.RaisePropertyChanged("jenis_kelamin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nama_agama {
            get {
                return this.nama_agamaField;
            }
            set {
                if ((object.ReferenceEquals(this.nama_agamaField, value) != true)) {
                    this.nama_agamaField = value;
                    this.RaisePropertyChanged("nama_agama");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nama_ayah {
            get {
                return this.nama_ayahField;
            }
            set {
                if ((object.ReferenceEquals(this.nama_ayahField, value) != true)) {
                    this.nama_ayahField = value;
                    this.RaisePropertyChanged("nama_ayah");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nama_ibu {
            get {
                return this.nama_ibuField;
            }
            set {
                if ((object.ReferenceEquals(this.nama_ibuField, value) != true)) {
                    this.nama_ibuField = value;
                    this.RaisePropertyChanged("nama_ibu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nama_siswa {
            get {
                return this.nama_siswaField;
            }
            set {
                if ((object.ReferenceEquals(this.nama_siswaField, value) != true)) {
                    this.nama_siswaField = value;
                    this.RaisePropertyChanged("nama_siswa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomor_ortu {
            get {
                return this.nomor_ortuField;
            }
            set {
                if ((object.ReferenceEquals(this.nomor_ortuField, value) != true)) {
                    this.nomor_ortuField = value;
                    this.RaisePropertyChanged("nomor_ortu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status_kawin {
            get {
                return this.status_kawinField;
            }
            set {
                if ((object.ReferenceEquals(this.status_kawinField, value) != true)) {
                    this.status_kawinField = value;
                    this.RaisePropertyChanged("status_kawin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tempat_lahir {
            get {
                return this.tempat_lahirField;
            }
            set {
                if ((object.ReferenceEquals(this.tempat_lahirField, value) != true)) {
                    this.tempat_lahirField = value;
                    this.RaisePropertyChanged("tempat_lahir");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tgl_lahir {
            get {
                return this.tgl_lahirField;
            }
            set {
                if ((object.ReferenceEquals(this.tgl_lahirField, value) != true)) {
                    this.tgl_lahirField = value;
                    this.RaisePropertyChanged("tgl_lahir");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WaliKelas", Namespace="http://schemas.datacontract.org/2004/07/RaporService")]
    [System.SerializableAttribute()]
    public partial class WaliKelas : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_kelasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_walikelasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nama_walikelasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passw_walikelasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string uname_walikelasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_kelas {
            get {
                return this.id_kelasField;
            }
            set {
                if ((object.ReferenceEquals(this.id_kelasField, value) != true)) {
                    this.id_kelasField = value;
                    this.RaisePropertyChanged("id_kelas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_walikelas {
            get {
                return this.id_walikelasField;
            }
            set {
                if ((object.ReferenceEquals(this.id_walikelasField, value) != true)) {
                    this.id_walikelasField = value;
                    this.RaisePropertyChanged("id_walikelas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nama_walikelas {
            get {
                return this.nama_walikelasField;
            }
            set {
                if ((object.ReferenceEquals(this.nama_walikelasField, value) != true)) {
                    this.nama_walikelasField = value;
                    this.RaisePropertyChanged("nama_walikelas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string passw_walikelas {
            get {
                return this.passw_walikelasField;
            }
            set {
                if ((object.ReferenceEquals(this.passw_walikelasField, value) != true)) {
                    this.passw_walikelasField = value;
                    this.RaisePropertyChanged("passw_walikelas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string uname_walikelas {
            get {
                return this.uname_walikelasField;
            }
            set {
                if ((object.ReferenceEquals(this.uname_walikelasField, value) != true)) {
                    this.uname_walikelasField = value;
                    this.RaisePropertyChanged("uname_walikelas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RaporServiceAzure.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAdmin", ReplyAction="http://tempuri.org/IService1/GetAdminResponse")]
        raporkuAPP.RaporServiceAzure.Admin[] GetAdmin();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAdmin", ReplyAction="http://tempuri.org/IService1/GetAdminResponse")]
        System.Threading.Tasks.Task<raporkuAPP.RaporServiceAzure.Admin[]> GetAdminAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetKelas", ReplyAction="http://tempuri.org/IService1/GetKelasResponse")]
        raporkuAPP.RaporServiceAzure.Kelas[] GetKelas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetKelas", ReplyAction="http://tempuri.org/IService1/GetKelasResponse")]
        System.Threading.Tasks.Task<raporkuAPP.RaporServiceAzure.Kelas[]> GetKelasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMapel", ReplyAction="http://tempuri.org/IService1/GetMapelResponse")]
        raporkuAPP.RaporServiceAzure.Mapel[] GetMapel();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMapel", ReplyAction="http://tempuri.org/IService1/GetMapelResponse")]
        System.Threading.Tasks.Task<raporkuAPP.RaporServiceAzure.Mapel[]> GetMapelAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRapot", ReplyAction="http://tempuri.org/IService1/GetRapotResponse")]
        raporkuAPP.RaporServiceAzure.Rapot[] GetRapot();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRapot", ReplyAction="http://tempuri.org/IService1/GetRapotResponse")]
        System.Threading.Tasks.Task<raporkuAPP.RaporServiceAzure.Rapot[]> GetRapotAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSiswa", ReplyAction="http://tempuri.org/IService1/GetSiswaResponse")]
        raporkuAPP.RaporServiceAzure.Siswa[] GetSiswa();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSiswa", ReplyAction="http://tempuri.org/IService1/GetSiswaResponse")]
        System.Threading.Tasks.Task<raporkuAPP.RaporServiceAzure.Siswa[]> GetSiswaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetWaliKelas", ReplyAction="http://tempuri.org/IService1/GetWaliKelasResponse")]
        raporkuAPP.RaporServiceAzure.WaliKelas[] GetWaliKelas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetWaliKelas", ReplyAction="http://tempuri.org/IService1/GetWaliKelasResponse")]
        System.Threading.Tasks.Task<raporkuAPP.RaporServiceAzure.WaliKelas[]> GetWaliKelasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LoginAdmin", ReplyAction="http://tempuri.org/IService1/LoginAdminResponse")]
        raporkuAPP.RaporServiceAzure.Admin LoginAdmin(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LoginAdmin", ReplyAction="http://tempuri.org/IService1/LoginAdminResponse")]
        System.Threading.Tasks.Task<raporkuAPP.RaporServiceAzure.Admin> LoginAdminAsync(string id);
        
        // CODEGEN: Generating message contract since the wrapper name (GetWalikelas) of message GetWalikelasRequest does not match the default value (GetWalikelas1)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetWalikelas", ReplyAction="http://tempuri.org/IService1/GetWalikelasResponse")]
        raporkuAPP.RaporServiceAzure.GetWalikelasResponse GetWalikelas1(raporkuAPP.RaporServiceAzure.GetWalikelasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetWalikelas", ReplyAction="http://tempuri.org/IService1/GetWalikelasResponse")]
        System.Threading.Tasks.Task<raporkuAPP.RaporServiceAzure.GetWalikelasResponse> GetWalikelas1Async(raporkuAPP.RaporServiceAzure.GetWalikelasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetKelasSiswa", ReplyAction="http://tempuri.org/IService1/GetKelasSiswaResponse")]
        raporkuAPP.RaporServiceAzure.Siswa[] GetKelasSiswa(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetKelasSiswa", ReplyAction="http://tempuri.org/IService1/GetKelasSiswaResponse")]
        System.Threading.Tasks.Task<raporkuAPP.RaporServiceAzure.Siswa[]> GetKelasSiswaAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNilaiRapot", ReplyAction="http://tempuri.org/IService1/GetNilaiRapotResponse")]
        raporkuAPP.RaporServiceAzure.Rapot[] GetNilaiRapot(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNilaiRapot", ReplyAction="http://tempuri.org/IService1/GetNilaiRapotResponse")]
        System.Threading.Tasks.Task<raporkuAPP.RaporServiceAzure.Rapot[]> GetNilaiRapotAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddDataKelas", ReplyAction="http://tempuri.org/IService1/AddDataKelasResponse")]
        string AddDataKelas(raporkuAPP.RaporServiceAzure.Kelas dp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddDataKelas", ReplyAction="http://tempuri.org/IService1/AddDataKelasResponse")]
        System.Threading.Tasks.Task<string> AddDataKelasAsync(raporkuAPP.RaporServiceAzure.Kelas dp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddDataMapel", ReplyAction="http://tempuri.org/IService1/AddDataMapelResponse")]
        string AddDataMapel(raporkuAPP.RaporServiceAzure.Mapel dp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddDataMapel", ReplyAction="http://tempuri.org/IService1/AddDataMapelResponse")]
        System.Threading.Tasks.Task<string> AddDataMapelAsync(raporkuAPP.RaporServiceAzure.Mapel dp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddDataRapot", ReplyAction="http://tempuri.org/IService1/AddDataRapotResponse")]
        string AddDataRapot(raporkuAPP.RaporServiceAzure.Rapot dp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddDataRapot", ReplyAction="http://tempuri.org/IService1/AddDataRapotResponse")]
        System.Threading.Tasks.Task<string> AddDataRapotAsync(raporkuAPP.RaporServiceAzure.Rapot dp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddDataSiswa", ReplyAction="http://tempuri.org/IService1/AddDataSiswaResponse")]
        string AddDataSiswa(raporkuAPP.RaporServiceAzure.Siswa dp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddDataSiswa", ReplyAction="http://tempuri.org/IService1/AddDataSiswaResponse")]
        System.Threading.Tasks.Task<string> AddDataSiswaAsync(raporkuAPP.RaporServiceAzure.Siswa dp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddDataWaliKelas", ReplyAction="http://tempuri.org/IService1/AddDataWaliKelasResponse")]
        string AddDataWaliKelas(raporkuAPP.RaporServiceAzure.WaliKelas dp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddDataWaliKelas", ReplyAction="http://tempuri.org/IService1/AddDataWaliKelasResponse")]
        System.Threading.Tasks.Task<string> AddDataWaliKelasAsync(raporkuAPP.RaporServiceAzure.WaliKelas dp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateDataWaliKelas", ReplyAction="http://tempuri.org/IService1/UpdateDataWaliKelasResponse")]
        string UpdateDataWaliKelas(raporkuAPP.RaporServiceAzure.WaliKelas dp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateDataWaliKelas", ReplyAction="http://tempuri.org/IService1/UpdateDataWaliKelasResponse")]
        System.Threading.Tasks.Task<string> UpdateDataWaliKelasAsync(raporkuAPP.RaporServiceAzure.WaliKelas dp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updatedatasiswa", ReplyAction="http://tempuri.org/IService1/updatedatasiswaResponse")]
        string updatedatasiswa(raporkuAPP.RaporServiceAzure.Siswa dp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updatedatasiswa", ReplyAction="http://tempuri.org/IService1/updatedatasiswaResponse")]
        System.Threading.Tasks.Task<string> updatedatasiswaAsync(raporkuAPP.RaporServiceAzure.Siswa dp);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetWalikelas", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetWalikelasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string id;
        
        public GetWalikelasRequest() {
        }
        
        public GetWalikelasRequest(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetWalikelasResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetWalikelasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public raporkuAPP.RaporServiceAzure.WaliKelas GetWalikelasResult;
        
        public GetWalikelasResponse() {
        }
        
        public GetWalikelasResponse(raporkuAPP.RaporServiceAzure.WaliKelas GetWalikelasResult) {
            this.GetWalikelasResult = GetWalikelasResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : raporkuAPP.RaporServiceAzure.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<raporkuAPP.RaporServiceAzure.IService1>, raporkuAPP.RaporServiceAzure.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public raporkuAPP.RaporServiceAzure.Admin[] GetAdmin() {
            return base.Channel.GetAdmin();
        }
        
        public System.Threading.Tasks.Task<raporkuAPP.RaporServiceAzure.Admin[]> GetAdminAsync() {
            return base.Channel.GetAdminAsync();
        }
        
        public raporkuAPP.RaporServiceAzure.Kelas[] GetKelas() {
            return base.Channel.GetKelas();
        }
        
        public System.Threading.Tasks.Task<raporkuAPP.RaporServiceAzure.Kelas[]> GetKelasAsync() {
            return base.Channel.GetKelasAsync();
        }
        
        public raporkuAPP.RaporServiceAzure.Mapel[] GetMapel() {
            return base.Channel.GetMapel();
        }
        
        public System.Threading.Tasks.Task<raporkuAPP.RaporServiceAzure.Mapel[]> GetMapelAsync() {
            return base.Channel.GetMapelAsync();
        }
        
        public raporkuAPP.RaporServiceAzure.Rapot[] GetRapot() {
            return base.Channel.GetRapot();
        }
        
        public System.Threading.Tasks.Task<raporkuAPP.RaporServiceAzure.Rapot[]> GetRapotAsync() {
            return base.Channel.GetRapotAsync();
        }
        
        public raporkuAPP.RaporServiceAzure.Siswa[] GetSiswa() {
            return base.Channel.GetSiswa();
        }
        
        public System.Threading.Tasks.Task<raporkuAPP.RaporServiceAzure.Siswa[]> GetSiswaAsync() {
            return base.Channel.GetSiswaAsync();
        }
        
        public raporkuAPP.RaporServiceAzure.WaliKelas[] GetWaliKelas() {
            return base.Channel.GetWaliKelas();
        }
        
        public System.Threading.Tasks.Task<raporkuAPP.RaporServiceAzure.WaliKelas[]> GetWaliKelasAsync() {
            return base.Channel.GetWaliKelasAsync();
        }
        
        public raporkuAPP.RaporServiceAzure.Admin LoginAdmin(string id) {
            return base.Channel.LoginAdmin(id);
        }
        
        public System.Threading.Tasks.Task<raporkuAPP.RaporServiceAzure.Admin> LoginAdminAsync(string id) {
            return base.Channel.LoginAdminAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        raporkuAPP.RaporServiceAzure.GetWalikelasResponse raporkuAPP.RaporServiceAzure.IService1.GetWalikelas1(raporkuAPP.RaporServiceAzure.GetWalikelasRequest request) {
            return base.Channel.GetWalikelas1(request);
        }
        
        public raporkuAPP.RaporServiceAzure.WaliKelas GetWalikelas1(string id) {
            raporkuAPP.RaporServiceAzure.GetWalikelasRequest inValue = new raporkuAPP.RaporServiceAzure.GetWalikelasRequest();
            inValue.id = id;
            raporkuAPP.RaporServiceAzure.GetWalikelasResponse retVal = ((raporkuAPP.RaporServiceAzure.IService1)(this)).GetWalikelas1(inValue);
            return retVal.GetWalikelasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<raporkuAPP.RaporServiceAzure.GetWalikelasResponse> raporkuAPP.RaporServiceAzure.IService1.GetWalikelas1Async(raporkuAPP.RaporServiceAzure.GetWalikelasRequest request) {
            return base.Channel.GetWalikelas1Async(request);
        }
        
        public System.Threading.Tasks.Task<raporkuAPP.RaporServiceAzure.GetWalikelasResponse> GetWalikelas1Async(string id) {
            raporkuAPP.RaporServiceAzure.GetWalikelasRequest inValue = new raporkuAPP.RaporServiceAzure.GetWalikelasRequest();
            inValue.id = id;
            return ((raporkuAPP.RaporServiceAzure.IService1)(this)).GetWalikelas1Async(inValue);
        }
        
        public raporkuAPP.RaporServiceAzure.Siswa[] GetKelasSiswa(string id) {
            return base.Channel.GetKelasSiswa(id);
        }
        
        public System.Threading.Tasks.Task<raporkuAPP.RaporServiceAzure.Siswa[]> GetKelasSiswaAsync(string id) {
            return base.Channel.GetKelasSiswaAsync(id);
        }
        
        public raporkuAPP.RaporServiceAzure.Rapot[] GetNilaiRapot(string id) {
            return base.Channel.GetNilaiRapot(id);
        }
        
        public System.Threading.Tasks.Task<raporkuAPP.RaporServiceAzure.Rapot[]> GetNilaiRapotAsync(string id) {
            return base.Channel.GetNilaiRapotAsync(id);
        }
        
        public string AddDataKelas(raporkuAPP.RaporServiceAzure.Kelas dp) {
            return base.Channel.AddDataKelas(dp);
        }
        
        public System.Threading.Tasks.Task<string> AddDataKelasAsync(raporkuAPP.RaporServiceAzure.Kelas dp) {
            return base.Channel.AddDataKelasAsync(dp);
        }
        
        public string AddDataMapel(raporkuAPP.RaporServiceAzure.Mapel dp) {
            return base.Channel.AddDataMapel(dp);
        }
        
        public System.Threading.Tasks.Task<string> AddDataMapelAsync(raporkuAPP.RaporServiceAzure.Mapel dp) {
            return base.Channel.AddDataMapelAsync(dp);
        }
        
        public string AddDataRapot(raporkuAPP.RaporServiceAzure.Rapot dp) {
            return base.Channel.AddDataRapot(dp);
        }
        
        public System.Threading.Tasks.Task<string> AddDataRapotAsync(raporkuAPP.RaporServiceAzure.Rapot dp) {
            return base.Channel.AddDataRapotAsync(dp);
        }
        
        public string AddDataSiswa(raporkuAPP.RaporServiceAzure.Siswa dp) {
            return base.Channel.AddDataSiswa(dp);
        }
        
        public System.Threading.Tasks.Task<string> AddDataSiswaAsync(raporkuAPP.RaporServiceAzure.Siswa dp) {
            return base.Channel.AddDataSiswaAsync(dp);
        }
        
        public string AddDataWaliKelas(raporkuAPP.RaporServiceAzure.WaliKelas dp) {
            return base.Channel.AddDataWaliKelas(dp);
        }
        
        public System.Threading.Tasks.Task<string> AddDataWaliKelasAsync(raporkuAPP.RaporServiceAzure.WaliKelas dp) {
            return base.Channel.AddDataWaliKelasAsync(dp);
        }
        
        public string UpdateDataWaliKelas(raporkuAPP.RaporServiceAzure.WaliKelas dp) {
            return base.Channel.UpdateDataWaliKelas(dp);
        }
        
        public System.Threading.Tasks.Task<string> UpdateDataWaliKelasAsync(raporkuAPP.RaporServiceAzure.WaliKelas dp) {
            return base.Channel.UpdateDataWaliKelasAsync(dp);
        }
        
        public string updatedatasiswa(raporkuAPP.RaporServiceAzure.Siswa dp) {
            return base.Channel.updatedatasiswa(dp);
        }
        
        public System.Threading.Tasks.Task<string> updatedatasiswaAsync(raporkuAPP.RaporServiceAzure.Siswa dp) {
            return base.Channel.updatedatasiswaAsync(dp);
        }
    }
}
